module.exports = {
	RECEIVE_DATA: "RECEIVE_DATA",
	MY_EVENT: "MY_EVENT", 
	ONE_VISIBLE: "ONE_VISIBLE",
  	ONE_REMOVE: "ONE_REMOVE",
  	TWO_VISIBLE: "TWO_VISIBLE",
	TWO_REMOVE: "TWO_VISIBLE",
	SHOW_LOGIN: "SHOW_LOGIN",
	SHOW_ARTICLES: "SHOW_ARTICLES",
	SHOW_TAGS: "SHOW_TAGS",
	SHOW_TOP25: "SHOW_TOP25",
	REMOVE_LOGIN: "REMOVE_LOGIN",
	REMOVE_ARTICLES: "REMOVE_ARTICLES",
	REMOVE_TAGS: "REMOVE_TAGS",
	REMOVE_TOP25: "REMOVE_TOP25"
}

